// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StegoEmbed() {
  return window['go']['main']['App']['StegoEmbed']();
}

export function StegoExtract(arg1, arg2, arg3) {
  return window['go']['main']['App']['StegoExtract'](arg1, arg2, arg3);
}
