// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Notify(arg1:string):Promise<void>;

export function NotifyError(arg1:string):Promise<void>;

export function StegoEmbed():Promise<string>;

export function StegoExtract(arg1:Array<number>,arg2:number,arg3:number):Promise<Array<number>>;
